name: プラグインリクエスト
description: マーケットプレイスに追加してほしいプラグインをリクエストする
labels: ["plugin-request"]
body:
  - type: textarea
    id: description
    attributes:
      label: プラグインの概要
      description: どのようなプラグインが欲しいか説明してください
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: ユースケース
      description: このプラグインをどのような場面で使いたいですか？
    validations:
      required: true

  - type: input
    id: existing
    attributes:
      label: 既存の実装やリポジトリ
      description: 参考になるリポジトリやツールがあればURLを記載してください
      placeholder: "https://github.com/..."
    validations:
      required: false
